# Generated by Django 2.2.2 on 2019-07-18 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productattributs_values',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=200, null=True)),
                ('attr_id', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'product_attribute_values',
            },
        ),
        migrations.CreateModel(
            name='Productimage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=200, null=True)),
                ('bo_id', models.CharField(max_length=200, null=True)),
                ('pro_image', models.CharField(max_length=250, null=True)),
                ('featured_image', models.CharField(max_length=250, null=True)),
                ('image_added_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('image_update_by', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product_image',
            },
        ),
        migrations.CreateModel(
            name='Productmaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_bo_id', models.CharField(max_length=200, null=True)),
                ('pro_name', models.CharField(max_length=500, null=True)),
                ('pro_bo_sku', models.CharField(max_length=250, null=True)),
                ('pro_cat_id', models.CharField(max_length=250, null=True)),
                ('pro_brand', models.CharField(max_length=250, null=True)),
                ('pro_price', models.CharField(max_length=250, null=True)),
                ('pro_qty', models.CharField(max_length=250, null=True)),
                ('pro_vat', models.CharField(max_length=250, null=True)),
                ('pro_attr', models.CharField(max_length=200, null=True)),
                ('pro_weight', models.CharField(max_length=200, null=True)),
                ('pro_desc', models.TextField(null=True)),
                ('pro_spec', models.TextField(null=True)),
                ('pro_shipping_price', models.CharField(max_length=200, null=True)),
                ('pro_cod', models.CharField(max_length=150, null=True)),
                ('pro_exchange_offer', models.CharField(max_length=200, null=True)),
                ('pro_featured', models.CharField(max_length=150, null=True)),
                ('pro_status', models.CharField(max_length=150, null=True)),
                ('pro_publish_by', models.CharField(max_length=200, null=True)),
                ('pro_add_date', models.CharField(max_length=200, null=True)),
                ('pro_edit_date', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product_master',
            },
        ),
        migrations.CreateModel(
            name='Productprice_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('added_at', models.DateTimeField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product_price_history',
            },
        ),
        migrations.CreateModel(
            name='Productquantity_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_id', models.CharField(max_length=200, null=True)),
                ('qty', models.CharField(max_length=200, null=True)),
                ('added_at', models.DateTimeField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'product_quantity_history',
            },
        ),
    ]
