# Generated by Django 2.2.2 on 2019-07-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributs_values',
            name='attr_unit',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
