# Generated by Django 2.2.2 on 2019-07-18 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productattributs_values_attr_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='pro_image',
            field=models.ImageField(null=True, upload_to='address_gallery'),
        ),
    ]
