# Generated by Django 2.2.2 on 2019-07-18 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190718_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_added_by',
            field=models.DateTimeField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image_update_by',
            field=models.DateTimeField(max_length=250, null=True),
        ),
    ]
