# Generated by Django 2.2.2 on 2019-07-19 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190718_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image_added_by',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
