# Generated by Django 2.2.2 on 2019-07-20 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190719_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='pro_add_date',
            field=models.DateField(null=True),
        ),
    ]
