# Generated by Django 2.2.2 on 2019-07-20 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190720_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='pro_featured',
            field=models.BooleanField(default=False),
        ),
    ]
