# Generated by Django 2.2.2 on 2019-07-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190720_0556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='pro_cod',
            field=models.BooleanField(default=False),
        ),
    ]
