# Generated by Django 2.2.2 on 2019-07-20 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190720_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='pro_brand',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
