# Generated by Django 2.2.2 on 2019-07-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20190723_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmaster',
            old_name='pro_qty',
            new_name='offline_pro_qty',
        ),
        migrations.RenameField(
            model_name='productquantity_history',
            old_name='qty',
            new_name='offline_qty',
        ),
        migrations.AddField(
            model_name='productmaster',
            name='online_pro_qty',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productquantity_history',
            name='online_qty',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
