# Generated by Django 2.2.2 on 2019-07-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20190724_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaster',
            name='offline_pro_qty',
            field=models.CharField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='online_pro_qty',
            field=models.CharField(default=0, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='productmaster',
            name='pro_status',
            field=models.IntegerField(help_text='0 => Publish,1 => Unpublish', null=True),
        ),
    ]
