# Generated by Django 2.2.2 on 2019-07-24 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0005_auto_20190720_1033'),
        ('product', '0015_auto_20190724_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmaster',
            name='pro_price_currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currency.Currency'),
        ),
    ]
