# Generated by Django 2.2.2 on 2019-07-20 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_by',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='user_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
