# Generated by Django 2.2.2 on 2019-07-20 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0002_auto_20190720_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.Country'),
        ),
    ]
