# Generated by Django 2.2.2 on 2019-07-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_auto_20190720_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='country_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Country'),
        ),
    ]
