# Generated by Django 2.2.2 on 2019-07-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=500)),
                ('country_code', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'country_master',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=100)),
                ('language_code', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'language_master',
            },
        ),
        migrations.CreateModel(
            name='Log_conversation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_id', models.CharField(max_length=100, null=True)),
                ('content_table', models.CharField(max_length=250, null=True)),
                ('operation', models.CharField(max_length=250, null=True)),
                ('operator_id', models.CharField(max_length=250, null=True)),
                ('log_create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('operator_type', models.CharField(max_length=200, null=True)),
                ('operation_lang', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'log_conversation',
            },
        ),
        migrations.CreateModel(
            name='Verify_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=250, null=True)),
                ('verify_start_date', models.CharField(max_length=250, null=True)),
                ('verify_end_date', models.CharField(max_length=250, null=True)),
                ('verification_status', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]
