# Generated by Django 2.2.2 on 2019-07-20 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20190720_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Country'),
        ),
    ]
