# Generated by Django 2.2.2 on 2019-07-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_language_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='writing_mode',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
