# Generated by Django 2.2.2 on 2019-07-20 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='primary_city_id',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
