# Generated by Django 2.2.2 on 2019-07-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_city_primary_city_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='language',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
