# Generated by Django 2.2.2 on 2019-07-20 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_city_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='common.Language'),
        ),
    ]
