# Generated by Django 2.2.2 on 2019-07-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_code', models.CharField(max_length=10, null=True)),
                ('user_id', models.CharField(max_length=10, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('validity', models.CharField(default=10, max_length=10)),
            ],
            options={
                'db_table': 'verification_code_master',
            },
        ),
    ]
