# Generated by Django 2.2.2 on 2019-07-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_verificationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='created_at',
            new_name='start_time',
        ),
        migrations.RemoveField(
            model_name='verificationcode',
            name='validity',
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
