# Generated by Django 2.2.2 on 2019-07-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_verificationcode_verification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='start_time',
            field=models.DateTimeField(max_length=10, null=True),
        ),
    ]
