# Generated by Django 2.2.2 on 2019-07-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190724_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
