# Generated by Django 2.2.2 on 2019-07-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190725_0555'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='forgot_password_pin',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
