# Generated by Django 2.2.2 on 2019-07-21 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category_master',
            name='category_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category_master',
            name='category_user_type',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='category_master',
            name='category_created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category_master',
            name='category_updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
